#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/sm8475-common

PRODUCT_COPY_FILES += \
    vendor/motorola/sm8475-common/proprietary/product/etc/permissions/UimGba.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimGba.xml \
    vendor/motorola/sm8475-common/proprietary/product/etc/permissions/UimGbaManager.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimGbaManager.xml \
    vendor/motorola/sm8475-common/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/motorola/sm8475-common/proprietary/system/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-qti.xml \
    vendor/motorola/sm8475-common/proprietary/system/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/qti_whitelist.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/init/qspmsvc.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/qspmsvc.rc \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/init/vendor.qti.hardware.qccsyshal@1.2-service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/vendor.qti.hardware.qccsyshal@1.2-service.rc \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/moto-telephony.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/moto-telephony.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/permissions/vendor.qti.ims.rcsservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.qti.ims.rcsservice.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/sysconfig/qti_telephony_system_packages_config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_telephony_system_packages_config.xml \
    vendor/motorola/sm8475-common/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/ap_gain.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain.bin \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/ap_gain_mmul.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain_mmul.bin \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile7.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile7.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU660.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU660.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU670.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU670.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU720.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU720.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU7__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU7__.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU820.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU820.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU830.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU830.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU860.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU860.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU8__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU8__.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/dpm_vndr/vendor.dpm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/dpm_vndr/vendor.dpm.conf \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/hdr_tm_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_tm_config.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-strongbox-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-strongbox-service-qti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service-qti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/imsdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdaemon.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.embmssl_server.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.embmssl_server.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.qdmastats.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qdmastats.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.spdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spdaemon.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.spuservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spuservice.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.vendor.qti.spu@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.qti.spu@1.1-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init.vendor.wlan.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.wlan.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/modemManager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/modemManager.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/motorola.hardware.camera.desktop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.camera.desktop@2.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/poweropt-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/poweropt-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qapeservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qapeservice.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qconfig.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qconfig.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qcrilNrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrilNrd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qesdk-manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qesdk-manager.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qms.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qms.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.dpmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dpmd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.eid@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.eid@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.iop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.iop@2.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.perf-hal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf-hal-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.media.c2audio@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2audio@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.qspmhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.qspmhal@1.0-service.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.sensors.qesdk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qesdk.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/AdaptLaunchFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AdaptLaunchFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/AppClassifierFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AppClassifierFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/LightningLaunchesFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/LightningLaunchesFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/PreKillFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/PreKillFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/ProCompFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/ProCompFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/QAPE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QAPE.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/QGPE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QGPE.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/QGPEActionMap.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/QGPEActionMap.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/SilkyScrollsFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/SilkyScrollsFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/prekill/prekill_2GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_2GB.data \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/prekill/prekill_4GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_4GB.data \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/prekill/prekill_6GB.data:$(TARGET_COPY_OUT_VENDOR)/etc/lm/prekill/prekill_6GB.data \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/lm/sPLHFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/sPLHFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/media_cape/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_cape/video_system_specs.json \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/media_codecs_cape.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_cape.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/media_codecs_performance_cape.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_cape.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/media_profiles_cape.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_cape.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/avcsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/avcsysnodesconfigs.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/perf/targetsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetsysnodesconfigs.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/pwr/PSMPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PSMPowerOptFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/pwr/PowerFeatureConfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/PowerFeatureConfig.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/pwr/StandbyFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/StandbyFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/pwr/VendorScenarioPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VendorScenarioPowerOptFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/pwr/VideoPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VideoPowerOptFeature.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcom_widevine_licenses.pfm:$(TARGET_COPY_OUT_VENDOR)/etc/qcom_widevine_licenses.pfm \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/10.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/10.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/11.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/11.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/12.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/12.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/13.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/13.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/6.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/6.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/7.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/7.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/8.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/8.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/config/9.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/9.0_config.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/0_initial.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/10_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/10_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/11_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/11_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/12_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/12_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/13_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/13_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/14_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/14_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/15_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/15_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/16_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/16_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/17_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/17_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/18_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/18_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/19_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/19_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/20_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/20_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/21_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/21_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/22_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/22_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/23_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/23_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/24_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/24_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/25_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/25_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/26_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/26_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/27_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/27_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/28_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/28_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/29_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/29_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/30_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/30_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/31_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/31_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/33_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/33_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/34_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/34_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/35_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/35_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/36_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/36_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/37_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/37_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/38_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/38_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/39_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/39_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/3_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/3_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/40_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/40_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/41_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/41_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/42_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/42_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/43_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/43_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/44_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/44_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/45_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/45_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/46_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/46_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/48_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/48_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/49_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/49_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/4_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/4_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/50_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/50_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/51_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/51_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/52_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/52_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/53_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/53_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/54_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/54_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/55_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/55_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/56_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/56_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/5_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/5_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/6_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/6_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/7_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/7_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/8_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/8_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/ecc/9_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/ecc/9_version_qcrildb.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/other/2_version_add_wps_config_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/2_version_add_wps_config_qcrilnr.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/other/3_version_update_wps_config_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/3_version_update_wps_config_qcrilnr.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/qcril_database/upgrade/other/6_version_change_property_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/6_version_change_property_table_qcrilnr.sql \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/c2audio.vendor.base-arm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/c2audio.vendor.base-arm.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/c2audio.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/c2audio.vendor.base-arm64.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/c2audio.vendor.ext-arm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/c2audio.vendor.ext-arm.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/c2audio.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/c2audio.vendor.ext-arm64.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm64.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm64.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/modemManager.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/modemManager.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/qapeservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qapeservice.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/qcrilnr@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qcrilnr@2.0.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/qesdk.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qesdk.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/qspm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qspm.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/sensors-qesdk.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/sensors-qesdk.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/motorola/sm8475-common/proprietary/vendor/etc/vhw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vhw.xml \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/CAMERA_ICP_480.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_480.elf \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/gmu_gen70000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70000.bin \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/venus_4mb.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_4mb.mbn \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/venus_4mb_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_4mb_unsigned.mbn \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/venus_4mb_v6.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_4mb_v6.mbn \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/venus_4mb_v7.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_4mb_v7.mbn \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/venus_v6.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_v6.mbn \
    vendor/motorola/sm8475-common/proprietary/vendor/firmware/venus_v7.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_v7.mbn \
    vendor/motorola/sm8475-common/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/motorola/sm8475-common/proprietary/vendor/gpu/kbc/unified_kbcs_32.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_32.bin \
    vendor/motorola/sm8475-common/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/motorola/sm8475-common/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    libCB \
    libOpenCL \
    libadreno_app_profiles \
    libadreno_utils \
    libgpudataproducer \
    libgsl \
    libkcl \
    libkernelmanager \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libvmmem \
    vendor.qti.qspmhal@1.0-impl \
    vendor.qti.qspmhal@1.0_vendor \
    btaudio_offload_if \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    deviceInfoServiceModuleNr \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    audio.bluetooth_qti.default \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.eid@1.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qccvndhal@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    vendor.qti.hardware.servicetracker@1.2-impl \
    vendor.qti.hardware.soter@1.0-impl \
    vulkan.adreno \
    lib-imscommon \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcsservice \
    lib-imsservice \
    lib-imsvtcore \
    lib-imsxml \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    libEvrcSwCodec \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQSEEComAPI \
    libQTEEConnector_listener \
    libQTEEConnector_vendor \
    libQcelp13SwCodec \
    libQnnHtp \
    libQnnHtpAltPrepV69Stub \
    libQnnHtpPrepare \
    libQnnHtpV69Stub \
    libQtiRilLoadable \
    libadaptlaunch \
    libadm \
    libadropbox \
    libadsp_default_listener \
    libadsprpc \
    libapengine \
    libappclassifier \
    libaualgo_foundation \
    libaudio_log_utils \
    libbacklight-calib \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbtnv \
    libcacertclient \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2uvvendor \
    libcdfw \
    libcdfw_remote_api \
    libcdsp_default_listener \
    libcdsprpc \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libcolor-default \
    libconfigdb \
    libcpion \
    libcv_common \
    libcvp2_1 \
    libdapparamstorage \
    libdataitems \
    libdiag \
    libdigital-dimming \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdpmqmihal \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsd2pcm \
    libdsi_netctrl \
    libdsutils \
    libeai_fixed \
    libeai_float \
    libembmsservice \
    libengineplugin \
    libeva \
    libfastcvdsp_stub \
    libfastcvopt \
    libgame_enhance \
    libgamepoweroptfeature \
    libgdtap \
    libgrpc++_unsecure_prebuilt \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhdrdynamic \
    libhdrdynamicootf \
    libidl \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    liblearningmodule \
    liblightninglaunches \
    liblistensoundmodel2vendor \
    liblmthermallistner \
    liblmutils-ns \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_base_util \
    libloc_eng_hub \
    libloc_mq_client \
    libloc_qwes_iface \
    libloc_ril_client \
    libloc_socket \
    libloc_util \
    liblocationservice \
    liblocationservice_glue \
    liblocdiagiface \
    liblog_vendor \
    liblowi_client \
    liblowi_common \
    liblowi_wifihal \
    liblqe \
    libmcs \
    libmdmcutback \
    libmdmdetect \
    libmdmimgload \
    libmdsprpc \
    libmemperfd \
    libmemutils \
    libmeters-ns \
    libmeters \
    libminkdescriptor \
    libminksocket_vendor \
    libmmosal_vendor \
    libmotext_inf \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_datapath_proxy \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnetmgr_sscm3 \
    libnetmgr_utils \
    libnetmgrext_interface_client \
    libnetmgrext_interface_server \
    libnetmgrmodemproxy \
    libnetmgrportutils \
    libnetmgrxfrmutils \
    libnlnetmgr \
    libops \
    libpal_net_if \
    libpasrutils \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libpowercore \
    libprekill \
    libprocomp \
    libpsmoptfeature \
    libqapesdk \
    libqc2audio_base \
    libqc2audio_basecodec \
    libqc2audio_core \
    libqc2audio_hooks \
    libqc2audio_hwaudiocodec \
    libqc2audio_platform \
    libqc2audio_swaudiocodec \
    libqc2audio_utils \
    libqc2colorconvertfilter \
    libqc2filter \
    libqc2vppfilter \
    libqcbor \
    libqcc_file_agent \
    libqcmaputils \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_filterbase \
    libqcodec2_hooks \
    libqcodec2_mockfilter \
    libqcodec2_mockqc2filter \
    libqcodec2_platform \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqcrilDataModule \
    libqcrilNr \
    libqcrilNrCellInfoModule \
    libqcrilNrFramework \
    libqcrilNrImsModule \
    libqcrilNrLogger \
    libqcrilNrPbmModule \
    libqcrilNrQtiBus \
    libqcrilNrQtiMutex \
    libqcrilNrSmsModule \
    libqcrilNrSocketModule \
    libqcrilNrVoiceModule \
    libqcrildataaidl \
    libqcrildatactl \
    libqcrildataqos \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdp \
    libqdpr \
    libqesdk \
    libqesdk_manager \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmimotext \
    libqmiservices \
    libqppe \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsocket \
    libqti-iopd-client \
    libqti-iopd \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libqti-utils \
    libqtigefar \
    libqtikeymaster4 \
    libqtikeymint \
    librcc \
    librcmask \
    libril-db \
    libril-legacy \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    librilqmimiscservices \
    librpmb \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsensorcal \
    libsensorslog \
    libshsc \
    libshsusr_verinfo \
    libsilkyscrolls \
    libskewknob \
    libslimclient \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsns_device_mode_stub \
    libsns_direct_channel_stub \
    libsnsapi \
    libsnsdiaglog \
    libsoc_helper \
    libspcom \
    libspl \
    libsplh \
    libssc \
    libssc_default_listener \
    libssd \
    libstandbyfeature \
    libsubsystem_control \
    libsys_info_cache \
    libsystem_health_mon \
    libtestutils \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libtrustedapploader \
    libtzdrmgenprov \
    libvendorscenariopoweroptfeature \
    libvideooptfeature \
    libvideotxr \
    libvideoutils \
    libvppcommon \
    libvpphcp \
    libvpphvx \
    libvppimmotion \
    libvpplibrary \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    motorola.hardware.camera.desktop@1.0 \
    motorola.hardware.camera.desktop@2.0 \
    motorola.hardware.sensors-V1-ndk_platform \
    qcrilInterfaces \
    qcrilMarshal \
    qcrilNrQmiModule \
    qcrilNr_aidl_IQtiRadioConfig \
    qcril_client \
    qcrild_libqcrilnr \
    qcrild_libqcrilnrutils \
    qti.video.utils.videobufferlayout \
    qtiPeripheralMgr \
    qtiril-utils \
    qtiwakelock \
    sensors.moto \
    sensors.ssc \
    libasphere \
    libmsstwrapper \
    libshoebox \
    libspeakerbundle \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.color@1.6 \
    vendor.display.color@1.7 \
    vendor.display.postproc@1.0 \
    vendor.libdpmctmgr \
    vendor.libdpmfdmgr \
    vendor.libdpmframework \
    vendor.libdpmtcm \
    vendor.libmwqemiptablemgr \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.factory@2.4 \
    vendor.qti.data.factory@2.5 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.gnss-V3-ndk_platform \
    vendor.qti.gnss-V5-ndk_platform \
    vendor.qti.gnss-service \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.1 \
    vendor.qti.hardware.data.cne.internal.server@1.2 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.connectionfactory-V1-ndk_platform \
    vendor.qti.hardware.data.dataactivity-V1-ndk_platform \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.1 \
    vendor.qti.hardware.data.flow@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.iwlan@1.1 \
    vendor.qti.hardware.data.ka-V1-ndk_platform \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.dpmservice@1.0 \
    vendor.qti.hardware.dpmservice@1.1 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.eid@1.0 \
    vendor.qti.hardware.embmssl@1.0 \
    vendor.qti.hardware.embmssl@1.1 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.power.powermodule@1.0 \
    vendor.qti.hardware.qccsyshal@1.0_vendor \
    vendor.qti.hardware.qccsyshal@1.1_vendor \
    vendor.qti.hardware.qccvndhal@1.0-halimpl \
    vendor.qti.hardware.qccvndhal@1.0 \
    vendor.qti.hardware.qconfig@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims-V12-ndk_platform \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.ims@1.8 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio-V8-ndk_platform \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.qtiradioconfig-V2-ndk_platform \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.trustedui@1.2 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@1.3 \
    vendor.qti.hardware.vpp@2.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.configservice@1.0 \
    vendor.qti.ims.configservice@1.1 \
    vendor.qti.ims.connection@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.factory@2.0 \
    vendor.qti.ims.factory@2.1 \
    vendor.qti.ims.factory@2.2 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.ims.rcssip@1.0 \
    vendor.qti.ims.rcssip@1.1 \
    vendor.qti.ims.rcssip@1.2 \
    vendor.qti.ims.rcsuce@1.0 \
    vendor.qti.ims.rcsuce@1.1 \
    vendor.qti.ims.rcsuce@1.2 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    vendor.qti.qesdhal@1.0 \
    vendor.qti.qesdhal@1.1-impl \
    vendor.qti.qesdhal@1.1 \
    vendor.qti.qesdsys-V1-ndk_platform \
    vendor.qti.spu@1.0 \
    vendor.qti.spu@1.1 \
    vendor.qti.spu@2.0 \
    vendor_lib_rfsa_adsp_bm2n00_bin \
    vendor_lib_rfsa_adsp_bm2n01_bin \
    vendor_lib_rfsa_adsp_bm2n02_bin \
    vendor_lib_rfsa_adsp_bm2n03_bin \
    vendor_lib_rfsa_adsp_bm2n04_bin \
    vendor_lib_rfsa_adsp_bm2n05_bin \
    vendor_lib_rfsa_adsp_bm2n06_bin \
    vendor_lib_rfsa_adsp_bm2n07_bin \
    vendor_lib_rfsa_adsp_bm2n10_bin \
    vendor_lib_rfsa_adsp_bm2n11_bin \
    vendor_lib_rfsa_adsp_bm2n12_bin \
    vendor_lib_rfsa_adsp_bm2n13_bin \
    vendor_lib_rfsa_adsp_bm2n14_bin \
    vendor_lib_rfsa_adsp_bm2n15_bin \
    vendor_lib_rfsa_adsp_bm2n16_bin \
    vendor_lib_rfsa_adsp_bm2n17_bin \
    vendor_lib_rfsa_adsp_bm2n18_bin \
    vendor_lib_rfsa_adsp_bm2n19_bin \
    vendor_lib_rfsa_adsp_bm2n20_bin \
    vendor_lib_rfsa_adsp_bm2n21_bin \
    vendor_lib_rfsa_adsp_bm2n22_bin \
    vendor_lib_rfsa_adsp_bm2n23_bin \
    vendor_lib_rfsa_adsp_bm2n24_bin \
    vendor_lib_rfsa_adsp_bm2n25_bin \
    vendor_lib_rfsa_adsp_bm2n26_bin \
    vendor_lib_rfsa_adsp_bm2n27_bin \
    vendor_lib_rfsa_adsp_bm2n31_bin \
    vendor_lib_rfsa_adsp_bm2n32_bin \
    vendor_lib_rfsa_adsp_bm2n33_bin \
    vendor_lib_rfsa_adsp_bm2n34_bin \
    vendor_lib_rfsa_adsp_bm2n35_bin \
    vendor_lib_rfsa_adsp_bm2n36_bin \
    vendor_lib_rfsa_adsp_bm2n37_bin \
    vendor_lib_rfsa_adsp_bm2n38_bin \
    vendor_lib_rfsa_adsp_bm2n39_bin \
    vendor_lib_rfsa_adsp_bm2n40_bin \
    vendor_lib_rfsa_adsp_bm2n41_bin \
    vendor_lib_rfsa_adsp_bm2n42_bin \
    vendor_lib_rfsa_adsp_bm2n43_bin \
    vendor_lib_rfsa_adsp_bm2n44_bin \
    vendor_lib_rfsa_adsp_bm2n45_bin \
    vendor_lib_rfsa_adsp_bm2n46_bin \
    vendor_lib_rfsa_adsp_bm2n47_bin \
    vendor_lib_rfsa_adsp_bm2n48_bin \
    vendor_lib_rfsa_adsp_bm2n49_bin \
    vendor_lib_rfsa_adsp_bm2n50_bin \
    vendor_lib_rfsa_adsp_bm2n51_bin \
    vendor_lib_rfsa_adsp_bm2n52_bin \
    vendor_lib_rfsa_adsp_bm2n53_bin \
    vendor_lib_rfsa_adsp_bm2n54_bin \
    vendor_lib_rfsa_adsp_bm2n55_bin \
    vendor_lib_rfsa_adsp_libDspIOProxy_skel_so \
    vendor_lib_rfsa_adsp_libQ6MSFR_manager_skel_so \
    vendor_lib_rfsa_adsp_libQnnHtpAltPrepV69Skel_so \
    vendor_lib_rfsa_adsp_libQnnHtpV69Skel_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV68Skel_so \
    vendor_lib_rfsa_adsp_libSnpeHtpV69Skel_so \
    vendor_lib_rfsa_adsp_libSuperSensor_skel_so \
    vendor_lib_rfsa_adsp_libVppFrcQnnHtp_so \
    vendor_lib_rfsa_adsp_libVppQnnHtp_so \
    vendor_lib_rfsa_adsp_libcalculator_skel_so \
    vendor_lib_rfsa_adsp_libcvpdsp_2_1_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libevadsp_3_0_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhalide_hexagon_remote_skel_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_networks_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_dsp_v65_domains_v2_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_dsp_v66_domains_v2_skel_so \
    vendor_lib_rfsa_adsp_libtracker_6dof_skel_8250_so \
    vendor_lib_rfsa_adsp_libtracker_6dof_skel_8350_so \
    vendor_lib_rfsa_adsp_libvpp_ais_networks_so \
    vendor_lib_rfsa_adsp_libvpp_vqa_networks_so \
    vendor_lib_rfsa_adsp_libvpt_action_recognition_so \
    vendor_lib_rfsa_adsp_libworker_pool_so \
    com.qualcomm.qti.dpm.api@1.0 \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libimscamera_jni \
    libimsmedia_jni \
    libmmosal \
    libmmparser_lite \
    libqcc_file_agent_sys \
    libqspmsvc \
    vendor.qti.ImsRtpService-V1-ndk \
    vendor.qti.diaghal-V1-ndk \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2-halimpl \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.imsrtpservice@3.0 \
    vendor.qti.imsrtpservice@3.1 \
    vendor.qti.qspmhal-V1-ndk \
    vendor.qti.qspmhal@1.0 \
    CACertService \
    CneApp \
    IWlanService \
    TimeService \
    uimgbaservice \
    ImsRcsService \
    QtiTelephonyService \
    QtiTelephony \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    tcmclient \
    uimgbalibrary \
    uimgbamanagerlibrary \
    uimservicelibrary \
    com.qti.dpmframework \
    dpmapi \
    moto-telephony \
    qcrilhook \
    vendor.qti.hardware.alarm-V1.0-java \
    vendor.qti.ims.connection-V1.0-java \
    vendor.qti.ims.connectionaidlservice-V1-java \
    vendor.qti.ims.factory-V2.0-java \
    vendor.qti.ims.factory-V2.1-java \
    vendor.qti.ims.factory-V2.2-java \
    vendor.qti.ims.factoryaidlservice-V1-java \
    vendor.qti.ims.rcssip-V1.0-java \
    vendor.qti.ims.rcssip-V1.1-java \
    vendor.qti.ims.rcssip-V1.2-java \
    vendor.qti.ims.rcssipaidlservice-V1-java \
    vendor.qti.ims.rcsuce-V1.0-java \
    vendor.qti.ims.rcsuce-V1.1-java \
    vendor.qti.ims.rcsuce-V1.2-java \
    vendor.qti.ims.rcsuceaidlservice-V1-java \
    android.hardware.security.keymint-service-qti.xml \
    c2_manifest_vendor_audio.xml \
    dataconnection-saidl.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    qtiradio-saidl.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.gnss-service.xml \
    vendor.qti.hardware.perf.xml \
    vendor.qti.hardware.qconfig@1.0-service.xml \
    vendor.qti.hardware.radio.ims.xml \
    vendor.qti.hardware.radio.qtiradioconfig.xml \
    vendor.qti.hardware.servicetracker@1.2-service.xml \
    vendor.qti.hardware.vpp@2.0-service.xml \
    adpl \
    adsprpcd \
    cdsprpcd \
    charge_only_mode \
    cnd \
    cnss-daemon \
    diag-router \
    dpmQmiMgr \
    dspservice \
    edgnss-daemon \
    embmsslServer \
    engine-service \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@4.0-strongbox-service-qti \
    android.hardware.keymaster@4.1-service-qti \
    android.hardware.security.keymint-service-qti \
    motorola.hardware.camera.desktop@2.0-service \
    qconfigservice \
    qcrilNrd \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.eid@1.0-service \
    vendor.qti.hardware.iop@2.0-service \
    vendor.qti.hardware.perf-hal-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    vendor.qti.hardware.servicetracker@1.2-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.media.c2@1.0-service \
    vendor.qti.media.c2audio@1.0-service \
    vendor.qti.spu@1.1-service \
    vendor.qti.spu@2.0-service \
    ims_rtp_daemon \
    imsdaemon \
    init.kernel.post_boot-cape \
    init.kernel.post_boot-diwali \
    init.kernel.post_boot-taro \
    init.kernel.post_boot \
    init.qcom.sensors \
    init.qti.kernel \
    init.qti.keymaster \
    init.qti.media \
    init.qti.qcv \
    ipacm-diag \
    irsc_util \
    ks \
    loadalgo \
    loc_launcher \
    lowi-server \
    mbm_spy \
    mlid \
    modemManager \
    motobox \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    perf_qesdk_client \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    poweropt-service \
    ppd \
    qcc-trd \
    qcom-system-daemon \
    qdcmss \
    qesdk-manager \
    qmi_motext_hook \
    qmipriod \
    qms \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qtigetprop \
    qtisetprop \
    rmt_storage \
    sec_nvm \
    sensors-qesdk \
    sensors.qti \
    shsusrd \
    spdaemon \
    sscrpcd \
    tftp_server \
    thermal-engine-v2 \
    time_daemon \
    vendor.dpmd \
    vendor.qti.hardware.soter@1.0-provision \
    vendor.qti.qspmhal@1.0-service \
    vendor_modprobe \
    vppservice \
    xtra-daemon \
    xtwifi-client \
    dpmd \
    qccsyshal@1.2-service \
    qspmsvc

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_bin_expat \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
